export const bookGenres = [
	"art",
	"art-history",
	"biography",
	"business",
	"comedy",
	"craft",
	"crime",
	"cultural-studies",
	"drama",
	"economics",
	"fantasy",
	"fiction",
	"historical-fiction",
	"history",
	"humor",
	"journalism",
	"literary-fiction",
	"memoir",
	"mystery",
	"mythology",
	"nautical",
	"non-fiction",
	"novella",
	"personal-development",
	"philosophy",
	"poetry",
	"politics",
	"productivity",
	"psychology",
	"religion",
	"romance",
	"science",
	"self-help",
	"social-criticism",
	"technology",
	"thriller",
	"travel",
] as const;

export type BookGenre = (typeof bookGenres)[number];

export const genreLabels: Record<BookGenre, string> = {
	"art": "Kunst",
	"art-history": "Kunstgeschichte",
	"biography": "Biografie",
	"business": "Wirtschaft",
	"comedy": "Komödie",
	"craft": "Handwerk",
	"crime": "Krimi",
	"cultural-studies": "Kulturwissenschaft",
	"drama": "Drama",
	"economics": "Volkswirtschaft",
	"fantasy": "Fantasy",
	"fiction": "Belletristik",
	"historical-fiction": "Historischer Roman",
	"history": "Geschichte",
	"humor": "Humor",
	"journalism": "Journalismus",
	"literary-fiction": "Literarische Fiktion",
	"memoir": "Memoiren",
	"mystery": "Rätsel",
	"mythology": "Mythologie",
	"nautical": "Seefahrt",
	"non-fiction": "Sachbuch",
	"novella": "Novelle",
	"personal-development": "Persönlichkeitsentwicklung",
	"philosophy": "Philosophie",
	"poetry": "Lyrik",
	"politics": "Politik",
	"productivity": "Produktivität",
	"psychology": "Psychologie",
	"religion": "Religion",
	"romance": "Liebesroman",
	"science": "Naturwissenschaft",
	"self-help": "Ratgeber",
	"social-criticism": "Gesellschaftskritik",
	"technology": "Technik",
	"thriller": "Thriller",
	"travel": "Reiseliteratur",
};
