export const genreLabels: Record<string, string> = {
	"art": "Kunst",
	"art-history": "Kunstgeschichte",
	"biography": "Biografie",
	"business": "Wirtschaft",
	"comedy": "Komödie",
	"craft": "Handwerk",
	"crime": "Krimi",
	"cultural-studies": "Kulturwissenschaft",
	"drama": "Drama",
	"economics": "Volkswirtschaft",
	"fantasy": "Fantasy",
	"fiction": "Belletristik",
	"historical-fiction": "Historischer Roman",
	"history": "Geschichte",
	"humor": "Humor",
	"journalism": "Journalismus",
	"literary-fiction": "Literarische Fiktion",
	"memoir": "Memoiren",
	"mystery": "Rätsel",
	"mythology": "Mythologie",
	"nautical": "Seefahrt",
	"non-fiction": "Sachbuch",
	"novella": "Novelle",
	"personal-development": "Persönlichkeitsentwicklung",
	"philosophy": "Philosophie",
	"poetry": "Lyrik",
	"politics": "Politik",
	"productivity": "Produktivität",
	"psychology": "Psychologie",
	"religion": "Religion",
	"romance": "Liebesroman",
	"science": "Naturwissenschaft",
	"self-help": "Ratgeber",
	"social-criticism": "Gesellschaftskritik",
	"technology": "Technik",
	"thriller": "Thriller",
	"travel": "Reiseliteratur",
};
